### PR TITLE
Update heading RegExp to conform to GFM/CommonMark

### PR DESCRIPTION
**Pull request by cribbles**
Requires a space between the hash and the heading markup. This conforms to the CommonMark spec and is necessary for Github compatibility.

See:

- https://github.com/github/markup/issues/1013#issuecomment-287060641
- https://blog.github.com/2017-03-14-a-formal-spec-for-github-flavored-markdown/

### CODE REVIEW

**Comment by zeusdeux** [comment]
@pdubroy Any updates on this?

**Comment by pdubroy** [comment]
How does the latest version of [marked](https://github.com/markedjs/marked) handle this case? From https://github.com/markedjs/marked/issues/692 it looks like the new behavior is exactly what you want. If so, I'd rather update this repo to the latest version of marked, as described [in the README](https://github.com/pdubroy/marked-ast#updating-marked).

**Comment by mohamedturki** [comment]
@pdubroy The latest version does not seem to solve the issue. See [this](https://github.com/markedjs/marked/issues/981).

**Comment by mohamedturki** [comment]
@pdubroy Any updates on this one? :)

**Comment by pdubroy** [comment]
@mohamedturki The issue linked seems to indicate to me that Marked now follows the spec and requires the space. If that is true I would rather just update this package to use the latest version of Marked. This package isn't intended to be a forked version of Marked that implements slightly different behavior.

If I'm wrong and Marked doesn't behave in the way this issue is describing, please post some console output and/or a gist demonstrating that — I'd like to be sure.

Thanks.

**Pull request closed without merging**
