### PR TITLE
Replace underscore with specific modules.

### PR DESCRIPTION
**Pull request by michaelrhodes**
Hey, great module! I've been using it in the browser, so I'm a bit sensitive about file size. By switching out the underscore library for [its specific functions](https://github.com/AmpersandJS/amp/tree/master/modules), I was able to shave to bundle size by a little over 50%.

```bash
# master
$ cat dist/marked-ast-bundle.js | wc -c
   79747

# patch/replace-underscore
$ cat dist/marked-ast-bundle.js | wc -c
   39278
```
I thought the dead-code removal feature of [uglifyjs](https://github.com/mishoo/UglifyJS2) might make this patch pointless, but it still manages to yield an 11kb saving after uglificiation.

```bash
# master
$ cat dist/marked-ast-bundle.js | uglifyjs -mc | wc -c
   33501

# patch/replace-underscore
$ cat dist/marked-ast-bundle.js | uglifyjs -mc | wc -c
   21851
```

### CODE REVIEW

**Comment by pdubroy** [comment]
Hey Michael, glad you've found it useful! And thanks for the pull request.

Given that these functions are pretty trivial and they are only used in a couple places, I'd prefer to just inline them and eliminate the dependency altogether. I just landed that in the [latest commit](https://github.com/pdubroy/marked-ast/commit/02a1f79710425ad04f30e2b5d2900fcffec610d7). If you're happy with that, I can go ahead and push it to NPM.

**Comment by michaelrhodes** [comment]
No problem! That's funny, my [original (unsent) pull request](https://github.com/michaelrhodes/marked-ast/blob/66f8d35d491c306396bb4832e8c2f47a04e91d24/index.js#L64) inlined _.each in the same way, but I ended up throwing it away because [`for in` loops are quite slow](http://jsperf.com/underscore-each-vs-for-in/4).

Actually, you could do away with all the inlined functions by just using native methods and telling IE8 to polyfill. In my original patch, I replaced `_.isArray` and `_.map` with their native counterparts, but I just realised, you could also replace  `_.each` with `Object.keys(node).forEach`. [Here’s how that would look](https://github.com/michaelrhodes/marked-ast/blob/patch/bundle-size/index.js).

**Comment by pdubroy** [comment]
AST nodes will never have very many keys, so I'd rather keep the code simple than worry about such a minor optimization. Who knows, one day it may be faster :-)

We could use native `map` and `isArray`, but for the time being I think I'm happy keeping this compatible with older browsers.

Thanks again!

**Comment by michaelrhodes** [comment]
Fair point, no worries! :)

**Pull request closed without merging**
